const { contextBridge, ipcRenderer } = require('electron')

const on = channel => fn => ipcRenderer.on(channel, (_, ...args) => fn(...args))

contextBridge.exposeInMainWorld('leech', {
  read: name => ipcRenderer.invoke('store:read', name),
  write: (name, value) => ipcRenderer.send('store:write', name, value),
  writeNow: (name, value) => ipcRenderer.sendSync('store:write-sync', name, value),
  window: what => ipcRenderer.send('window', what),
  look: look => ipcRenderer.send('look', look),
  openExternal: url => ipcRenderer.send('open-external', url),
  copy: text => ipcRenderer.send('copy', text),
  paste: () => ipcRenderer.invoke('paste'),
  menu: (items, at) => ipcRenderer.invoke('menu', items, at),
  importSources: () => ipcRenderer.invoke('import:sources'),
  importBookmarks: name => ipcRenderer.invoke('import:bookmarks', name),
  importHistory: name => ipcRenderer.invoke('import:history', name),
  importCSV: () => ipcRenderer.invoke('import:csv'),
  vault: (what, ...args) => ipcRenderer.invoke(`vault:${what}`, ...args),
  veil: (what, ...args) => ipcRenderer.send(`veil:${what}`, ...args),
  hiddenOn: host => ipcRenderer.invoke('veil:list', host),
  onHidden: on('hidden'),
  escapable: (on, veil) => ipcRenderer.send('escapable', on, veil),
  configure: config => ipcRenderer.send('configure', config),
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  defaultBrowser: make => ipcRenderer.invoke('default-browser', make),
  clear: what => ipcRenderer.invoke('clear', what),
  info: ipcRenderer.sendSync('info'),
  snapshot: id => ipcRenderer.invoke('snapshot', id),
  forgetPartition: partition => ipcRenderer.invoke('forget-partition', partition),
  downloads: () => ipcRenderer.invoke('downloads'),
  openFile: file => ipcRenderer.send('downloads:open', file),
  showFile: file => ipcRenderer.send('downloads:show', file),
  forgetDownload: file => ipcRenderer.send('downloads:remove', file),
  clearDownloads: () => ipcRenderer.send('downloads:clear'),
  answer: (id, allow) => ipcRenderer.send('answer', id, allow),
  onDownloads: on('downloads'),
  onAsk: on('ask'),
  onRemember: on('remember'),
  onShortcut: on('shortcut'),
  onOpenTab: on('open-tab'),
  onSearch: on('search'),
  onToast: on('toast'),
  onFlush: on('flush'),
  onMaximized: on('maximized'),
  onFullscreen: on('fullscreen')
})
